---
name: cmpsc-101-fall-2018-lab6
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/main:
    java:
        labsix/experiment/Experiment.java:
            --multi 2 --language Java
            --fragment "TODO" --count 0 --exact
            --fragment "println(" --count 8 --exact
src/main:
    java:
        labsix/experiment/RunCampaign.java:
            --multi 4 --language Java
            --fragment "TODO" --count 0 --exact
            --fragment "println(" --count 5 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 6 --exact
    --words 100
# --> check the number of commits beyond a threshold
--commits 15
# --> check that the program executes and produces 4 lines of output
# --> check that the program produces output with certain fragments
--command "gradle -q --console plain run" --executes
